export enum CategoriesEnum{
    INCOMING="Входящие",
    OUTGOING="Исходящее",
}
export enum ChannelsEnum{
    CHAT="CHAT",
    PHONE="PHONE",
    EMAIL="EMAIL",
}
export enum InitiatorTypeEnum{
    CLIENT="CHAT",
    NOT_CLIENT="PHONE",
    PRODUCT="PRODUCT",
    DELIVERY="DELIVERY",
    OTHER="OTHER",
}
export enum ClaimTypesEnum {
    ERROR = "ERROR",
    NAVIGATION = "NAVIGATION",
    INQUIRY = "INQUIRY",
    DATA_UPDATE = "DATA_UPDATE",
    CONSULTATION = "CONSULTATION",
    CLOSE_ACCOUNT = "CLOSE_ACCOUNT",
    CURRENCY_CONTROL = "CURRENCY_CONTROL",
    CB_REQUEST = "CB_REQUEST",
    NEW_SERVICE = "NEW_SERVICE",
    PROFILE_MANAGEMENT = "PROFILE_MANAGEMENT",
    UNKNOWN = "UNKNOWN",
    EXTRA_ACCOUNT = "EXTRA_ACCOUNT",
    TARIFF_CHANGE = "TARIFF_CHANGE",
    NOMINAL_PAYMENT = "NOMINAL_PAYMENT",
    CLAIM = "CLAIM",
    OTHER = "OTHER"
}
export enum ClaimThemesEnum {
    IS_ROWI = "IS_ROWI",
    CHAT = "CHAT",
    IBANK = "IBANK",
    ACCOUNT_OPEN_INQUIRY = "ACCOUNT_OPEN_INQUIRY",
    CASH_FLOW_INQUIRY = "CASH_FLOW_INQUIRY",
    ACCOUNT_CLOSE_INQUIRY = "ACCOUNT_CLOSE_INQUIRY",
    CARD_INDEX_INQUIRY = "CARD_INDEX_INQUIRY",
    LOAN_DEBT_INQUIRY = "LOAN_DEBT_INQUIRY",
    EXCERPT = "EXCERPT",
    VISIT_TO_CLIENT = "VISIT_TO_CLIENT",
    NO_VISIT_TO_CLIENT = "NO_VISIT_TO_CLIENT",
    TARIFFS = "TARIFFS",
    DOCUMENTS = "DOCUMENTS",
    ACCOUNT_BLOCK = "ACCOUNT_BLOCK",
    PAYMENTS = "PAYMENTS",
    INTEREST_ON_BALANCE = "INTEREST_ON_BALANCE",
    INITIATED_BY_CLIENT = "INITIATED_BY_CLIENT",
    DOCUMENTS_REQUEST = "DOCUMENTS_REQUEST",
    BANK_SUPPORT_OF_CONTRACT = "BANK_SUPPORT_OF_CONTRACT",
    SUPPORT_OF_PREGIVEN_ACPT = "SUPPORT_OF_PREGIVEN_ACPT",
    CREATE_NEW_PROFILE = "CREATE_NEW_PROFILE",
    BLOCK_PROFILE = "BLOCK_PROFILE",
    UNBLOCK_PROFILE = "UNBLOCK_PROFILE",
    LEGAL_SUPPORT_REQUIRED = "LEGAL_SUPPORT_REQUIRED",
    LEGAL_SUPPORT_NOT_REQUIRED = "LEGAL_SUPPORT_NOT_REQUIRED",
    OTHER = "OTHER"
}